/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
export const indexTemplateHtml = `<div class="markdown-tip"><div class="markdown-tip-item" v-for="data in datas" :key="data.text" @mouseenter="mouseenter(data, $event)" @mouseleave="mouseleave(data)"><span class="markdown-tip-item-text">{{data.text}}</span><pre :class="titleClass" v-if="data.text === visibleText">{{data.title}}</pre></div></div>`;
