/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { MarkdownTip } from "./index"

// @ts-ignore
export function indexTemplateHtml(this: MarkdownTip) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"markdown-tip"},_vm._l((_vm.datas),function(data){return _c('div',{key:data.text,staticClass:"markdown-tip-item",on:{"mouseenter":function($event){_vm.mouseenter(data, $event)},"mouseleave":function($event){_vm.mouseleave(data)}}},[_c('span',{staticClass:"markdown-tip-item-text"},[_vm._v(_vm._s(data.text))]),_vm._v(" "),(data.text === _vm.visibleText)?_c('pre',{class:_vm.titleClass},[_vm._v(_vm._s(data.title))]):_vm._e()])}))}
// @ts-ignore
export var indexTemplateHtmlStatic = [  ]
// tslint:enable
