// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
import { createBlock as _createBlock, createCommentVNode as _createCommentVNode, createVNode as _createVNode, Fragment as _Fragment, openBlock as _openBlock, renderList as _renderList, toDisplayString as _toDisplayString } from 'vue'
// tslint:disable
/* eslint-disable */

export function indexTemplateHtml(_ctx, _cache) {
  return (_openBlock(), _createBlock("div", { class: "markdown-tip" }, [
    (_openBlock(true), _createBlock(_Fragment, null, _renderList(_ctx.datas, (data) => {
      return (_openBlock(), _createBlock("div", {
        class: "markdown-tip-item",
        key: data.text,
        onMouseenter: $event => (_ctx.mouseenter(data, $event)),
        onMouseleave: $event => (_ctx.mouseleave(data))
      }, [
        _createVNode("span", { class: "markdown-tip-item-text" }, _toDisplayString(data.text), 1 /* TEXT */),
        (data.text === _ctx.visibleText)
          ? (_openBlock(), _createBlock("pre", {
              key: 0,
              class: _ctx.titleClass
            }, _toDisplayString(data.title), 3 /* TEXT, CLASS */))
          : _createCommentVNode("v-if", true)
      ], 40 /* PROPS, HYDRATE_EVENTS */, ["onMouseenter", "onMouseleave"]))
    }), 128 /* KEYED_FRAGMENT */))
  ]))
}
/* eslint-enable */
// tslint:enable
